In [6]:
import numpy as np

a = np.array([(7,8,9,10,11,12,13), (17,18,19,20,21,22,23)])

print(a)

print(a.sum)


[[ 7  8  9 10 11 12 13]
 [17 18 19 20 21 22 23]]
<built-in method sum of numpy.ndarray object at 0x000002199D771B30>


In [7]:
print(a.sum(axis=None)) # total sum

210


In [8]:
print(a.sum(axis=0)) # calc along the row


[24 26 28 30 32 34 36]


In [9]:
print(a.sum(axis=1)) # calc along the col

[ 70 140]


In [10]:
print(a.mean(axis=None))

15.0


In [11]:
print(a.mean(axis=0))

[12. 13. 14. 15. 16. 17. 18.]


In [12]:
print(a.mean(axis=1))

[10. 20.]


In [13]:
# Variance
print(a.var(axis=None))

29.0


In [17]:
# Standard deviation
print(a.std(axis=None))

5.385164807134504


In [18]:
print(a.min(axis=None))

7


In [19]:
print(a.max(axis=None))

23
