In [11]:
import numpy as np

In [12]:
a=np.array([1,2,3])
print(a)
print(a.dtype)

[1 2 3]
int32


In [14]:
a=np.array([1.3,2.4,3.0] , dtype=np.float16)
print(a)
print(a.dtype)

[1.3 2.4 3. ]
float16


In [15]:
a=np.array([1,2,3])
b=a
b[0]=42
print(b)
print(a)

[42  2  3]
[42  2  3]


In [17]:
a=np.array([1,2,3])
b=a.copy()
b[0]=42
print(b)
print(a)

[42  2  3]
[1 2 3]


### Array initialization

In [18]:
a=np.zeros((2,3))
print(a)


[[0. 0. 0.]
 [0. 0. 0.]]


In [20]:
a=np.ones((2,3))
print(a)
print(a.dtype)

[[1. 1. 1.]
 [1. 1. 1.]]
float64


In [21]:
a=np.full((2,3),5.0)
print(a)

[[5. 5. 5.]
 [5. 5. 5.]]


In [23]:
a=np.eye(3)  # 3x3 matrix
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [28]:
a=np.arange(20)  # arrange numbers from 0 to 20
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [30]:
a=np.linspace(0,10,5)  # 0 is the start entry , 10 is the stop entry , 5 is the number of values that should be present in the array i.e 5
print(a)

[ 0.   2.5  5.   7.5 10. ]
