In [1]:
import numpy as np

In [3]:
a=np.random.random((3,2))
print(a)
# This will generate array from uniform distribution from 0 to 1


[[0.51529429 0.55579662]
 [0.38226546 0.16661244]
 [0.92787498 0.94188934]]


In [6]:
# Also there is gausian distribution with mean=0 and variance=1
a=np.random.randn(1000)  # normal / gaussian  
print(a.mean(),a.var())

-0.035200577419675506 1.0401880064890847


In [7]:
a=np.random.randint(3,10,size=(3,3)) # this will generate a 3x3 matrix of integers between 3 and 9
print(a)

[[8 9 7]
 [9 8 5]
 [4 5 8]]


In [9]:
a=np.random.randint(10,size=(3,3)) # Here 0 is lower bound and 9 is upper bound
print(a)

[[3 1 8]
 [5 7 7]
 [9 0 2]]


In [10]:
a=np.random.choice(5, size=10) # this will generate an array of size 10 and will choose random numbers between 0 and 4
print(a)

[3 2 2 1 0 4 1 4 0 0]


In [12]:
a=np.random.choice([5,-3, -8], size=10)
print(a)

[-8  5 -3 -8  5 -3  5 -8  5  5]
