### NUMPY:- Core library for scientific computations in Python. Essential for Data Science, ML, DL.It is a core package for many ML libraries like Scikit-learn,matplotlib,pandas,etc. Numpy provides high performance in multidimentional arrays. It also provides tools for the mathematical operations with arrays.

### Usecase: Array/matrix operation - Linear Algebra, Dot product, Matrix multiplications, linear systems, inverse determinant, eigen vectors, random numbers, working with images represented as array

#### Installing Numpy:- pip install numpy

In [1]:

import numpy as np
print(np.__version__)

1.26.4


In [5]:
a=np.array([1,2,3,4,5])
print(a)


[1 2 3 4 5]


In [6]:
print(a.shape) # shape- shape of array
print(a.dtype) # dtype- datatype of array
print(a.ndim)  # ndim- number of dimensions of array
print(a.size)
print(a.itemsize)
print(a[0])
a[0]=10
print(a)

(5,)
int32
1
5
4
1
[10  2  3  4  5]


In [7]:
# Operations of arrays

b=a*np.array([6,7,8,9,1])
print(b)

[60 14 24 36  5]
