In [1]:
import numpy as np
l=[1,2,3]
a=np.array([1,2,3])


In [2]:
# l.append(4)
l=l+[4] # for appending in list
l=l*2   # repeats the list
print(l)
a=a+np.array([4])  # add 4 to the existing elements of the array
# a=a*2  # multiply 2 with existing elements of array
print(a)

[1, 2, 3, 4, 1, 2, 3, 4]
[5 6 7]


In [3]:
a=np.array([3,4,5])
# Square Root
a=np.sqrt(a)
print(a)
# Log
a=np.log(a)
print(a)


[1.73205081 2.         2.23606798]
[0.54930614 0.69314718 0.80471896]
