In [2]:
import numpy as np
a=np.array([[1,2],[3,4]])
print(a.shape)
print(a[0,0])

(2, 2)
1


### Transpose


In [3]:
print(a.T)

[[1 3]
 [2 4]]


### Inverse

In [4]:
print(np.linalg.inv(a))

[[-2.   1. ]
 [ 1.5 -0.5]]


### Determinant

In [5]:
print(np.linalg.det(a))


-2.0000000000000004


### Diagonal

In [6]:
b=np.diag(a)
print(np.diag(b))

[[1 0]
 [0 4]]


### Indexing

In [7]:
c=np.array([[1,2],[3,4]])
print(c)

[[1 2]
 [3 4]]
