In [1]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a.shape)
print(a[0,0])

(2, 4)
1


### Slicing

In [2]:

print(a[0,:])  # row 0 and colon for the other dimension
print(a[0:,])
print(a[:,0])
print(a[:0,])
print(a[0,1:3])
print(a[:,1])
print(a[:,2])
print(a[-1,-1]) # last row and last column
print(a[-1,-2]) # last row and second last column


[1 2 3 4]
[[1 2 3 4]
 [5 6 7 8]]
[1 5]
[]
[2 3]
[2 6]
[3 7]
8
7


### Indexing

In [4]:

c=np.array([[1,2],[3,4]])
print(c)

d=c[0,1]
print(d)

b=np.array([[1,2],[3,4],[5,6]])
print(b)




[[1 2]
 [3 4]]
2
[[1 2]
 [3 4]
 [5 6]]


### Boolean Indexing

In [8]:
bool_indx=b>2
print(bool_indx)
print(b[bool_indx])

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]


In [9]:
print(b[b>2])

[3 4 5 6]


In [10]:
c=np.where(b>2, b, -1)
print(c)

[[-1 -1]
 [ 3  4]
 [ 5  6]]


In [18]:
d = np.array([10, 20, 30, 40, 50, 41, 91, 62])
print(d)

e = [1, 3, 5]
print(d[e])

[10 20 30 40 50 41 91 62]
[20 40 41]


### For printing even

In [24]:
f = np.array([10, 20, 30, 40, 50, 41, 91, 62])
even=np.argwhere(f%2==0).flatten()
print(even)

[0 1 2 3 4 7]


In [25]:
f = np.array([10, 20, 30, 40, 50, 41, 91, 62])
even_values = f[f % 2 == 0]
print(even_values)

[10 20 30 40 50 62]
