### Reshaping array

In [2]:
import numpy as np
a=np.arange(1,7)
print(a)
print(a.shape)

[1 2 3 4 5 6]
(6,)


In [11]:
b=a.reshape((2,3))
print(b)


[[1 2 3]
 [4 5 6]]


In [12]:
b=a.reshape((3,2))
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [13]:
c=b[np.newaxis, :]
print(c.shape)

(1, 3, 2)


In [14]:
c=b[:, np.newaxis]
# print(c.shape)
print(c)

[[[1 2]]

 [[3 4]]

 [[5 6]]]
