### Concatenation

In [4]:
import numpy as np
a=np.array([[1,2],[3,4]])
print(a)
b=np.array([[5,6]])
c=np.concatenate((a,b))
print(c)


[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]


In [5]:
c=np.concatenate((a,b), axis=None) #flatten
print(c)

[1 2 3 4 5 6]


In [6]:
c=np.concatenate((a,b.T), axis=1) 
print(c)

[[1 2 5]
 [3 4 6]]


### hstack (hosrizontal stack) :It will stack the array columnwise

In [7]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

c=np.hstack((a,b))
print(c)

[1 2 3 4 5 6 7 8]


### vstack (vertical stack) :It will stack the array vertically

In [8]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

c=np.vstack((a,b))
print(c)

[[1 2 3 4]
 [5 6 7 8]]
