### Broadcasting :Powerful mechanism that allows Numpy to work with arrays of different shapes when performing arithematic operations

In [1]:
import numpy as np


In [4]:
x = np.array([[1,2,3], [4,5,6], [1,2,3], [4,5,6]])

a = np.array([1,0,1])

y = x + a

print(y)

[[2 2 4]
 [5 5 7]
 [2 2 4]
 [5 5 7]]
